/* Generated by I from src/main.i (header). Do not edit. */
#pragma once
#include <core.h>
#include <stddef.h>

#define max_alloc_size 0x10000000000

#include "runtime/memops_os.h"
#include "stdlib.h"
#include "stdio.h"
#include "string.h"

#line 1 "<generated>"
#ifndef I_REFLECT_TYPES_DEFINED
#define I_REFLECT_TYPES_DEFINED
typedef enum i_reflect_type_kind {
    I_Reflect_Type_Name,
    I_Reflect_Type_Ptr,
    I_Reflect_Type_Generic,
    I_Reflect_Type_Array,
    I_Reflect_Type_Proc,
} i_reflect_type_kind;

typedef struct i_reflect_field {
    const char *name;
    const char *type;
    const char *attrs;
    u64 offset;
    u64 size;
    u64 align;
    i_reflect_type_kind kind;
    u64 array_count;
    u64 pointer_depth;
    const char *base_type;
    const char *elem_type;
    const char *generic_arg_type;
    u64 is_const;
} i_reflect_field;

typedef struct i_reflect_type {
    const char *name;
    u64 size;
    u64 align;
    u64 field_count;
    const i_reflect_field *fields;
} i_reflect_type;

typedef struct i_reflect_enum_value {
    const char *name;
    i32 value;
} i_reflect_enum_value;

typedef struct i_reflect_enum {
    const char *name;
    u64 size;
    u64 align;
    u64 value_count;
    const i_reflect_enum_value *values;
} i_reflect_enum;

#if defined(__clang__) || defined(__GNUC__)
#define I_REFLECT_INLINE static inline __attribute__((unused))
#else
#define I_REFLECT_INLINE static inline
#endif

I_REFLECT_INLINE const char *i_reflect_type_kind_name(i_reflect_type_kind kind) {
    switch (kind) {
        case I_Reflect_Type_Name: return "name";
        case I_Reflect_Type_Ptr: return "ptr";
        case I_Reflect_Type_Generic: return "generic";
        case I_Reflect_Type_Array: return "array";
        case I_Reflect_Type_Proc: return "proc";
    }
    return "unknown";
}

I_REFLECT_INLINE int i_reflect_field_is_pointer(const i_reflect_field *field) {
    return field && field->pointer_depth > 0;
}

I_REFLECT_INLINE int i_reflect_field_is_array(const i_reflect_field *field) {
    return field && (field->kind == I_Reflect_Type_Array || field->array_count > 0);
}

I_REFLECT_INLINE int i_reflect_field_is_generic(const i_reflect_field *field) {
    return field && (field->kind == I_Reflect_Type_Generic || (field->generic_arg_type && field->generic_arg_type[0]));
}

I_REFLECT_INLINE u64 i_reflect_count_fields_with_kind(const i_reflect_type *type, i_reflect_type_kind kind) {
    if (!type) return 0;
    u64 count = 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (type->fields[i].kind == kind) count++;
    }
    return count;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_with_kind(const i_reflect_type *type, i_reflect_type_kind kind) {
    if (!type) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (type->fields[i].kind == kind) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_next_field_with_kind(const i_reflect_type *type, i_reflect_type_kind kind, const i_reflect_field *after) {
    if (!type) return 0;
    u64 start = 0;
    if (after) {
        for (u64 i = 0; i < type->field_count; i++) {
            if (&type->fields[i] == after) { start = i + 1; break; }
        }
    }
    for (u64 i = start; i < type->field_count; i++) {
        if (type->fields[i].kind == kind) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE int i_reflect_cstr_equal(const char *a, const char *b) {
    if (!a || !b) return 0;
    while (*a && *b && *a == *b) { a++; b++; }
    return *a == 0 && *b == 0;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field(const i_reflect_type *type, const char *name) {
    if (!type || !name) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (i_reflect_cstr_equal(type->fields[i].name, name)) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE u64 i_reflect_field_index(const i_reflect_type *type, const i_reflect_field *field, u64 fallback) {
    if (!type || !field) return fallback;
    for (u64 i = 0; i < type->field_count; i++) {
        if (&type->fields[i] == field) return i;
    }
    return fallback;
}

I_REFLECT_INLINE u64 i_reflect_find_field_index(const i_reflect_type *type, const char *name, u64 fallback) {
    const i_reflect_field *field = i_reflect_find_field(type, name);
    return i_reflect_field_index(type, field, fallback);
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_field_at(const i_reflect_type *type, u64 index) {
    if (!type || index >= type->field_count) return 0;
    return &type->fields[index];
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_by_offset(const i_reflect_type *type, u64 offset) {
    if (!type) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (type->fields[i].offset == offset) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE u64 i_reflect_field_end_offset(const i_reflect_field *field) {
    if (!field) return 0;
    return field->offset + field->size;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_containing_offset(const i_reflect_type *type, u64 offset) {
    if (!type) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        u64 start = type->fields[i].offset;
        u64 end = i_reflect_field_end_offset(&type->fields[i]);
        if (start <= offset && offset < end) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE void *i_reflect_field_ptr(void *base, const i_reflect_field *field) {
    if (!base || !field) return 0;
    return (void *)((unsigned char *)base + field->offset);
}

I_REFLECT_INLINE const void *i_reflect_field_const_ptr(const void *base, const i_reflect_field *field) {
    if (!base || !field) return 0;
    return (const void *)((const unsigned char *)base + field->offset);
}

I_REFLECT_INLINE int i_reflect_field_copy(void *dst_base, const void *src_base, const i_reflect_field *field) {
    void *dst = i_reflect_field_ptr(dst_base, field);
    const void *src = i_reflect_field_const_ptr(src_base, field);
    if (!dst || !src) return 0;
    memmove(dst, src, (size_t)field->size);
    return 1;
}

I_REFLECT_INLINE int i_reflect_field_zero(void *base, const i_reflect_field *field) {
    void *dst = i_reflect_field_ptr(base, field);
    if (!dst) return 0;
    memset(dst, 0, (size_t)field->size);
    return 1;
}

I_REFLECT_INLINE int i_reflect_field_copy_by_name(void *dst_base, const void *src_base, const i_reflect_type *type, const char *name) {
    return i_reflect_field_copy(dst_base, src_base, i_reflect_find_field(type, name));
}

I_REFLECT_INLINE int i_reflect_field_zero_by_name(void *base, const i_reflect_type *type, const char *name) {
    return i_reflect_field_zero(base, i_reflect_find_field(type, name));
}

I_REFLECT_INLINE int i_reflect_attr_is_sep(char c) {
    return c == 0 || c == ',' || c == ' ' || c == '\t' || c == '\r' || c == '\n';
}

I_REFLECT_INLINE int i_reflect_field_has_attr(const i_reflect_field *field, const char *attr) {
    if (!field || !field->attrs || !attr || !attr[0]) return 0;
    const char *scan = field->attrs;
    while (*scan) {
        while (*scan == ',' || *scan == ' ' || *scan == '\t' || *scan == '\r' || *scan == '\n') scan++;
        const char *token = scan;
        while (*scan && !i_reflect_attr_is_sep(*scan)) scan++;
        const char *a = token;
        const char *b = attr;
        while (a < scan && *b && *a == *b) { a++; b++; }
        if (a == scan && *b == 0) return 1;
    }
    return 0;
}

I_REFLECT_INLINE u64 i_reflect_count_fields_with_attr(const i_reflect_type *type, const char *attr) {
    if (!type || !attr || !attr[0]) return 0;
    u64 count = 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (i_reflect_field_has_attr(&type->fields[i], attr)) count++;
    }
    return count;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_with_attr(const i_reflect_type *type, const char *attr) {
    if (!type || !attr || !attr[0]) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (i_reflect_field_has_attr(&type->fields[i], attr)) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_next_field_with_attr(const i_reflect_type *type, const char *attr, const i_reflect_field *after) {
    if (!type || !attr || !attr[0]) return 0;
    u64 start = 0;
    if (after) {
        for (u64 i = 0; i < type->field_count; i++) {
            if (&type->fields[i] == after) { start = i + 1; break; }
        }
    }
    for (u64 i = start; i < type->field_count; i++) {
        if (i_reflect_field_has_attr(&type->fields[i], attr)) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_enum_value *i_reflect_find_enum_value_by_name(const i_reflect_enum *type, const char *name) {
    if (!type || !name) return 0;
    for (u64 i = 0; i < type->value_count; i++) {
        if (i_reflect_cstr_equal(type->values[i].name, name)) return &type->values[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_enum_value *i_reflect_find_enum_value_by_value(const i_reflect_enum *type, i32 value) {
    if (!type) return 0;
    for (u64 i = 0; i < type->value_count; i++) {
        if (type->values[i].value == value) return &type->values[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_enum_value *i_reflect_enum_value_at(const i_reflect_enum *type, u64 index) {
    if (!type || index >= type->value_count) return 0;
    return &type->values[index];
}

I_REFLECT_INLINE const char *i_reflect_enum_name_from_value(const i_reflect_enum *type, i32 value) {
    const i_reflect_enum_value *found = i_reflect_find_enum_value_by_value(type, value);
    return found ? found->name : 0;
}

I_REFLECT_INLINE i32 i_reflect_enum_value_from_name(const i_reflect_enum *type, const char *name, i32 fallback) {
    const i_reflect_enum_value *found = i_reflect_find_enum_value_by_name(type, name);
    return found ? found->value : fallback;
}

#undef I_REFLECT_INLINE

#endif

structdecl(memops_arena);
structdecl(memops_arena_temp);
structdecl(payload);
structdecl(Array_payload);
structdecl(Array_i32);
structdecl(Node_payload);
structdecl(List_payload);


#line 13 "C:\\devel\\i\\src\\runtime\\memops.i"
structdef(memops_arena) {
#line 14 "C:\\devel\\i\\src\\runtime\\memops.i"
    u8 * base;
#line 15 "C:\\devel\\i\\src\\runtime\\memops.i"
    u8 * cursor;
#line 16 "C:\\devel\\i\\src\\runtime\\memops.i"
    u8 * previous;
#line 17 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 used;
#line 18 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 pagesize;
#line 19 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 npages;
};

#line 22 "C:\\devel\\i\\src\\runtime\\memops.i"
structdef(memops_arena_temp) {
#line 23 "C:\\devel\\i\\src\\runtime\\memops.i"
    memops_arena * arena;
#line 24 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 used;
};

#line 1 "<generated>"
/* I monomorph: struct Array<T> -> Array_payload; declared at C:\devel\i\src\runtime\Array.i:4:1 */
#line 4 "C:\\devel\\i\\src\\runtime\\Array.i"
structdef(Array_payload) {
#line 5 "C:\\devel\\i\\src\\runtime\\Array.i"
    payload * data;
#line 6 "C:\\devel\\i\\src\\runtime\\Array.i"
    u64 length;
};

#line 1 "<generated>"
/* I monomorph: struct Array<T> -> Array_i32; declared at C:\devel\i\src\runtime\Array.i:4:1 */
#line 4 "C:\\devel\\i\\src\\runtime\\Array.i"
structdef(Array_i32) {
#line 5 "C:\\devel\\i\\src\\runtime\\Array.i"
    i32 * data;
#line 6 "C:\\devel\\i\\src\\runtime\\Array.i"
    u64 length;
};

#line 1 "<generated>"
/* I monomorph: struct Node<T> -> Node_payload; declared at C:\devel\i\src\runtime\Node.i:4:1 */
#line 4 "C:\\devel\\i\\src\\runtime\\Node.i"
structdef(Node_payload) {
#line 5 "C:\\devel\\i\\src\\runtime\\Node.i"
    Node_payload * next;
#line 6 "C:\\devel\\i\\src\\runtime\\Node.i"
    payload data;
};

#line 1 "<generated>"
/* I monomorph: struct List<T> -> List_payload; declared at C:\devel\i\src\runtime\List.i:5:1 */
#line 5 "C:\\devel\\i\\src\\runtime\\List.i"
structdef(List_payload) {
#line 6 "C:\\devel\\i\\src\\runtime\\List.i"
    Node_payload * head;
#line 7 "C:\\devel\\i\\src\\runtime\\List.i"
    usize length;
};

#line 5 "src/main.i"
structdef(payload) {
#line 6 "src/main.i"
    f32 x;
#line 7 "src/main.i"
    u8 * y;
};

#line 1 "<generated>"
extern const i_reflect_type memops_arena_reflect;
#define memops_arena_reflected memops_arena_reflect
#line 1 "<generated>"
extern const i_reflect_type memops_arena_temp_reflect;
#define memops_arena_temp_reflected memops_arena_temp_reflect
#line 1 "<generated>"
extern const i_reflect_type payload_reflect;
#define payload_reflected payload_reflect
#line 1 "<generated>"
extern const i_reflect_type Array_payload_reflect;
#define Array_payload_reflected Array_payload_reflect
#line 1 "<generated>"
extern const i_reflect_type Array_i32_reflect;
#define Array_i32_reflected Array_i32_reflect
#line 1 "<generated>"
extern const i_reflect_type Node_payload_reflect;
#define Node_payload_reflected Node_payload_reflect
#line 1 "<generated>"
extern const i_reflect_type List_payload_reflect;
#define List_payload_reflected List_payload_reflect


#line 27 "C:\\devel\\i\\src\\runtime\\memops.i"
bool memops_is_power_of_two(usize x);
#line 31 "C:\\devel\\i\\src\\runtime\\memops.i"
usize memops_align_forward(usize ptr, usize align);
#line 41 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_initialize(memops_arena * arena);
#line 53 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_push(memops_arena * arena, u64 alloc_size, u64 align);
#line 87 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_push_zero(memops_arena * arena, u64 alloc_size, u64 align);
#line 93 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_get_pos(memops_arena * arena);
#line 97 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_set_pos(memops_arena * arena, void * pos);
#line 103 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_pop(memops_arena * arena, u64 alloc_size);
#line 109 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_realloc_(memops_arena * arena, u64 new_alloc_size, void * old_ptr, u64 old_alloc_size, u64 align);
#line 115 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_clear(memops_arena * arena);
#line 120 "C:\\devel\\i\\src\\runtime\\memops.i"
memops_arena_temp memops_arena_temp_begin(memops_arena * arena);
#line 127 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_temp_end(memops_arena_temp temp);
#line 10 "src/main.i"
i32 main(i32 argc, char * * argv);
#line 1 "<generated>"
/* I monomorph: proc Array<T>reserve -> Array_payload_reserve; declared at C:\devel\i\src\runtime\Array.i:9:1; instantiated at src/main.i:28:32 */
#line 9 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_payload Array_payload_reserve(memops_arena * arena, u64 length);
#line 1 "<generated>"
/* I monomorph: proc Array<T>reserve -> Array_i32_reserve; declared at C:\devel\i\src\runtime\Array.i:9:1; instantiated at src/main.i:35:27 */
#line 9 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_i32 Array_i32_reserve(memops_arena * arena, u64 length);
#line 1 "<generated>"
/* I monomorph: proc Node<T>create -> Node_payload_create; declared at C:\devel\i\src\runtime\Node.i:9:1; instantiated at C:\devel\i\src\runtime\List.i:20:22 */
#line 9 "C:\\devel\\i\\src\\runtime\\Node.i"
Node_payload * Node_payload_create(memops_arena * arena, payload data);
#line 1 "<generated>"
/* I monomorph: proc List<T>create -> List_payload_create; declared at C:\devel\i\src\runtime\List.i:10:1; instantiated at src/main.i:44:19 */
#line 10 "C:\\devel\\i\\src\\runtime\\List.i"
List_payload * List_payload_create(memops_arena * arena);
#line 1 "<generated>"
/* I monomorph: proc List<T>append -> List_payload_append; declared at C:\devel\i\src\runtime\List.i:19:1; instantiated at src/main.i:45:5 */
#line 19 "C:\\devel\\i\\src\\runtime\\List.i"
void List_payload_append(memops_arena * arena, List_payload * list, payload item);
