/* Generated by I from src/main.i (source). Do not edit. */
#include <core.h>
#include <stddef.h>

#define max_alloc_size 0x10000000000

#include "runtime/memops_os.h"
#include "stdlib.h"
#include "stdio.h"
#include "string.h"

#line 1 "<generated>"
#ifndef I_REFLECT_TYPES_DEFINED
#define I_REFLECT_TYPES_DEFINED
typedef enum i_reflect_type_kind {
    I_Reflect_Type_Name,
    I_Reflect_Type_Ptr,
    I_Reflect_Type_Generic,
    I_Reflect_Type_Array,
    I_Reflect_Type_Proc,
} i_reflect_type_kind;

typedef struct i_reflect_field {
    const char *name;
    const char *type;
    const char *attrs;
    u64 offset;
    u64 size;
    u64 align;
    i_reflect_type_kind kind;
    u64 array_count;
    u64 pointer_depth;
    const char *base_type;
    const char *elem_type;
    const char *generic_arg_type;
    u64 is_const;
} i_reflect_field;

typedef struct i_reflect_type {
    const char *name;
    u64 size;
    u64 align;
    u64 field_count;
    const i_reflect_field *fields;
} i_reflect_type;

typedef struct i_reflect_enum_value {
    const char *name;
    i32 value;
} i_reflect_enum_value;

typedef struct i_reflect_enum {
    const char *name;
    u64 size;
    u64 align;
    u64 value_count;
    const i_reflect_enum_value *values;
} i_reflect_enum;

#if defined(__clang__) || defined(__GNUC__)
#define I_REFLECT_INLINE static inline __attribute__((unused))
#else
#define I_REFLECT_INLINE static inline
#endif

I_REFLECT_INLINE const char *i_reflect_type_kind_name(i_reflect_type_kind kind) {
    switch (kind) {
        case I_Reflect_Type_Name: return "name";
        case I_Reflect_Type_Ptr: return "ptr";
        case I_Reflect_Type_Generic: return "generic";
        case I_Reflect_Type_Array: return "array";
        case I_Reflect_Type_Proc: return "proc";
    }
    return "unknown";
}

I_REFLECT_INLINE int i_reflect_field_is_pointer(const i_reflect_field *field) {
    return field && field->pointer_depth > 0;
}

I_REFLECT_INLINE int i_reflect_field_is_array(const i_reflect_field *field) {
    return field && (field->kind == I_Reflect_Type_Array || field->array_count > 0);
}

I_REFLECT_INLINE int i_reflect_field_is_generic(const i_reflect_field *field) {
    return field && (field->kind == I_Reflect_Type_Generic || (field->generic_arg_type && field->generic_arg_type[0]));
}

I_REFLECT_INLINE u64 i_reflect_count_fields_with_kind(const i_reflect_type *type, i_reflect_type_kind kind) {
    if (!type) return 0;
    u64 count = 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (type->fields[i].kind == kind) count++;
    }
    return count;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_with_kind(const i_reflect_type *type, i_reflect_type_kind kind) {
    if (!type) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (type->fields[i].kind == kind) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_next_field_with_kind(const i_reflect_type *type, i_reflect_type_kind kind, const i_reflect_field *after) {
    if (!type) return 0;
    u64 start = 0;
    if (after) {
        for (u64 i = 0; i < type->field_count; i++) {
            if (&type->fields[i] == after) { start = i + 1; break; }
        }
    }
    for (u64 i = start; i < type->field_count; i++) {
        if (type->fields[i].kind == kind) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE int i_reflect_cstr_equal(const char *a, const char *b) {
    if (!a || !b) return 0;
    while (*a && *b && *a == *b) { a++; b++; }
    return *a == 0 && *b == 0;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field(const i_reflect_type *type, const char *name) {
    if (!type || !name) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (i_reflect_cstr_equal(type->fields[i].name, name)) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE u64 i_reflect_field_index(const i_reflect_type *type, const i_reflect_field *field, u64 fallback) {
    if (!type || !field) return fallback;
    for (u64 i = 0; i < type->field_count; i++) {
        if (&type->fields[i] == field) return i;
    }
    return fallback;
}

I_REFLECT_INLINE u64 i_reflect_find_field_index(const i_reflect_type *type, const char *name, u64 fallback) {
    const i_reflect_field *field = i_reflect_find_field(type, name);
    return i_reflect_field_index(type, field, fallback);
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_field_at(const i_reflect_type *type, u64 index) {
    if (!type || index >= type->field_count) return 0;
    return &type->fields[index];
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_by_offset(const i_reflect_type *type, u64 offset) {
    if (!type) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (type->fields[i].offset == offset) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE u64 i_reflect_field_end_offset(const i_reflect_field *field) {
    if (!field) return 0;
    return field->offset + field->size;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_containing_offset(const i_reflect_type *type, u64 offset) {
    if (!type) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        u64 start = type->fields[i].offset;
        u64 end = i_reflect_field_end_offset(&type->fields[i]);
        if (start <= offset && offset < end) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE void *i_reflect_field_ptr(void *base, const i_reflect_field *field) {
    if (!base || !field) return 0;
    return (void *)((unsigned char *)base + field->offset);
}

I_REFLECT_INLINE const void *i_reflect_field_const_ptr(const void *base, const i_reflect_field *field) {
    if (!base || !field) return 0;
    return (const void *)((const unsigned char *)base + field->offset);
}

I_REFLECT_INLINE int i_reflect_field_copy(void *dst_base, const void *src_base, const i_reflect_field *field) {
    void *dst = i_reflect_field_ptr(dst_base, field);
    const void *src = i_reflect_field_const_ptr(src_base, field);
    if (!dst || !src) return 0;
    memmove(dst, src, (size_t)field->size);
    return 1;
}

I_REFLECT_INLINE int i_reflect_field_zero(void *base, const i_reflect_field *field) {
    void *dst = i_reflect_field_ptr(base, field);
    if (!dst) return 0;
    memset(dst, 0, (size_t)field->size);
    return 1;
}

I_REFLECT_INLINE int i_reflect_field_copy_by_name(void *dst_base, const void *src_base, const i_reflect_type *type, const char *name) {
    return i_reflect_field_copy(dst_base, src_base, i_reflect_find_field(type, name));
}

I_REFLECT_INLINE int i_reflect_field_zero_by_name(void *base, const i_reflect_type *type, const char *name) {
    return i_reflect_field_zero(base, i_reflect_find_field(type, name));
}

I_REFLECT_INLINE int i_reflect_attr_is_sep(char c) {
    return c == 0 || c == ',' || c == ' ' || c == '\t' || c == '\r' || c == '\n';
}

I_REFLECT_INLINE int i_reflect_field_has_attr(const i_reflect_field *field, const char *attr) {
    if (!field || !field->attrs || !attr || !attr[0]) return 0;
    const char *scan = field->attrs;
    while (*scan) {
        while (*scan == ',' || *scan == ' ' || *scan == '\t' || *scan == '\r' || *scan == '\n') scan++;
        const char *token = scan;
        while (*scan && !i_reflect_attr_is_sep(*scan)) scan++;
        const char *a = token;
        const char *b = attr;
        while (a < scan && *b && *a == *b) { a++; b++; }
        if (a == scan && *b == 0) return 1;
    }
    return 0;
}

I_REFLECT_INLINE u64 i_reflect_count_fields_with_attr(const i_reflect_type *type, const char *attr) {
    if (!type || !attr || !attr[0]) return 0;
    u64 count = 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (i_reflect_field_has_attr(&type->fields[i], attr)) count++;
    }
    return count;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_find_field_with_attr(const i_reflect_type *type, const char *attr) {
    if (!type || !attr || !attr[0]) return 0;
    for (u64 i = 0; i < type->field_count; i++) {
        if (i_reflect_field_has_attr(&type->fields[i], attr)) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_field *i_reflect_next_field_with_attr(const i_reflect_type *type, const char *attr, const i_reflect_field *after) {
    if (!type || !attr || !attr[0]) return 0;
    u64 start = 0;
    if (after) {
        for (u64 i = 0; i < type->field_count; i++) {
            if (&type->fields[i] == after) { start = i + 1; break; }
        }
    }
    for (u64 i = start; i < type->field_count; i++) {
        if (i_reflect_field_has_attr(&type->fields[i], attr)) return &type->fields[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_enum_value *i_reflect_find_enum_value_by_name(const i_reflect_enum *type, const char *name) {
    if (!type || !name) return 0;
    for (u64 i = 0; i < type->value_count; i++) {
        if (i_reflect_cstr_equal(type->values[i].name, name)) return &type->values[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_enum_value *i_reflect_find_enum_value_by_value(const i_reflect_enum *type, i32 value) {
    if (!type) return 0;
    for (u64 i = 0; i < type->value_count; i++) {
        if (type->values[i].value == value) return &type->values[i];
    }
    return 0;
}

I_REFLECT_INLINE const i_reflect_enum_value *i_reflect_enum_value_at(const i_reflect_enum *type, u64 index) {
    if (!type || index >= type->value_count) return 0;
    return &type->values[index];
}

I_REFLECT_INLINE const char *i_reflect_enum_name_from_value(const i_reflect_enum *type, i32 value) {
    const i_reflect_enum_value *found = i_reflect_find_enum_value_by_value(type, value);
    return found ? found->name : 0;
}

I_REFLECT_INLINE i32 i_reflect_enum_value_from_name(const i_reflect_enum *type, const char *name, i32 fallback) {
    const i_reflect_enum_value *found = i_reflect_find_enum_value_by_name(type, name);
    return found ? found->value : fallback;
}

#undef I_REFLECT_INLINE

#endif

structdecl(memops_arena);
structdecl(memops_arena_temp);
structdecl(payload);
structdecl(Array_payload);
structdecl(Array_i32);
structdecl(Node_payload);
structdecl(List_payload);


#line 13 "C:\\devel\\i\\src\\runtime\\memops.i"
structdef(memops_arena) {
#line 14 "C:\\devel\\i\\src\\runtime\\memops.i"
    u8 * base;
#line 15 "C:\\devel\\i\\src\\runtime\\memops.i"
    u8 * cursor;
#line 16 "C:\\devel\\i\\src\\runtime\\memops.i"
    u8 * previous;
#line 17 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 used;
#line 18 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 pagesize;
#line 19 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 npages;
};

#line 22 "C:\\devel\\i\\src\\runtime\\memops.i"
structdef(memops_arena_temp) {
#line 23 "C:\\devel\\i\\src\\runtime\\memops.i"
    memops_arena * arena;
#line 24 "C:\\devel\\i\\src\\runtime\\memops.i"
    u64 used;
};

#line 1 "<generated>"
/* I monomorph: struct Array<T> -> Array_payload; declared at C:\devel\i\src\runtime\Array.i:4:1 */
#line 4 "C:\\devel\\i\\src\\runtime\\Array.i"
structdef(Array_payload) {
#line 5 "C:\\devel\\i\\src\\runtime\\Array.i"
    payload * data;
#line 6 "C:\\devel\\i\\src\\runtime\\Array.i"
    u64 length;
};

#line 1 "<generated>"
/* I monomorph: struct Array<T> -> Array_i32; declared at C:\devel\i\src\runtime\Array.i:4:1 */
#line 4 "C:\\devel\\i\\src\\runtime\\Array.i"
structdef(Array_i32) {
#line 5 "C:\\devel\\i\\src\\runtime\\Array.i"
    i32 * data;
#line 6 "C:\\devel\\i\\src\\runtime\\Array.i"
    u64 length;
};

#line 7 "src/main.i"
structdef(payload) {
#line 8 "src/main.i"
    f32 x;
#line 9 "src/main.i"
    u8 * y;
};

#line 1 "<generated>"
/* I monomorph: struct Node<T> -> Node_payload; declared at C:\devel\i\src\runtime\Node.i:4:1 */
#line 4 "C:\\devel\\i\\src\\runtime\\Node.i"
structdef(Node_payload) {
#line 5 "C:\\devel\\i\\src\\runtime\\Node.i"
    Node_payload * next;
#line 6 "C:\\devel\\i\\src\\runtime\\Node.i"
    payload data;
};

#line 1 "<generated>"
/* I monomorph: struct List<T> -> List_payload; declared at C:\devel\i\src\runtime\List.i:5:1 */
#line 5 "C:\\devel\\i\\src\\runtime\\List.i"
structdef(List_payload) {
#line 6 "C:\\devel\\i\\src\\runtime\\List.i"
    Node_payload * head;
#line 7 "C:\\devel\\i\\src\\runtime\\List.i"
    usize length;
};

#line 1 "<generated>"
static const i_reflect_field i_reflect_fields_Array_payload[] = {
    {"data", "ptr_payload", "", (u64)offsetof(Array_payload, data), (u64)sizeof(((Array_payload *)0)->data), (u64)__alignof__((( Array_payload *)0)->data), I_Reflect_Type_Ptr, 0, 1, "", "payload", "", 0},
    {"length", "u64", "", (u64)offsetof(Array_payload, length), (u64)sizeof(((Array_payload *)0)->length), (u64)__alignof__((( Array_payload *)0)->length), I_Reflect_Type_Name, 0, 0, "u64", "", "", 0},
};
const i_reflect_type Array_payload_reflect = {"Array_payload", (u64)sizeof(Array_payload), (u64)__alignof__(Array_payload), 2, i_reflect_fields_Array_payload};

#line 1 "<generated>"
static const i_reflect_field i_reflect_fields_Array_i32[] = {
    {"data", "ptr_i32", "", (u64)offsetof(Array_i32, data), (u64)sizeof(((Array_i32 *)0)->data), (u64)__alignof__((( Array_i32 *)0)->data), I_Reflect_Type_Ptr, 0, 1, "", "i32", "", 0},
    {"length", "u64", "", (u64)offsetof(Array_i32, length), (u64)sizeof(((Array_i32 *)0)->length), (u64)__alignof__((( Array_i32 *)0)->length), I_Reflect_Type_Name, 0, 0, "u64", "", "", 0},
};
const i_reflect_type Array_i32_reflect = {"Array_i32", (u64)sizeof(Array_i32), (u64)__alignof__(Array_i32), 2, i_reflect_fields_Array_i32};

#line 1 "<generated>"
static const i_reflect_field i_reflect_fields_Node_payload[] = {
    {"next", "ptr_Node_payload", "", (u64)offsetof(Node_payload, next), (u64)sizeof(((Node_payload *)0)->next), (u64)__alignof__((( Node_payload *)0)->next), I_Reflect_Type_Ptr, 0, 1, "", "Node_payload", "", 0},
    {"data", "payload", "", (u64)offsetof(Node_payload, data), (u64)sizeof(((Node_payload *)0)->data), (u64)__alignof__((( Node_payload *)0)->data), I_Reflect_Type_Name, 0, 0, "payload", "", "", 0},
};
const i_reflect_type Node_payload_reflect = {"Node_payload", (u64)sizeof(Node_payload), (u64)__alignof__(Node_payload), 2, i_reflect_fields_Node_payload};

#line 1 "<generated>"
static const i_reflect_field i_reflect_fields_List_payload[] = {
    {"head", "ptr_Node_payload", "", (u64)offsetof(List_payload, head), (u64)sizeof(((List_payload *)0)->head), (u64)__alignof__((( List_payload *)0)->head), I_Reflect_Type_Ptr, 0, 1, "", "Node_payload", "", 0},
    {"length", "usize", "", (u64)offsetof(List_payload, length), (u64)sizeof(((List_payload *)0)->length), (u64)__alignof__((( List_payload *)0)->length), I_Reflect_Type_Name, 0, 0, "usize", "", "", 0},
};
const i_reflect_type List_payload_reflect = {"List_payload", (u64)sizeof(List_payload), (u64)__alignof__(List_payload), 2, i_reflect_fields_List_payload};

#line 1 "<generated>"
static const i_reflect_field i_reflect_fields_memops_arena[] = {
    {"base", "ptr_u8", "", (u64)offsetof(memops_arena, base), (u64)sizeof(((memops_arena *)0)->base), (u64)__alignof__((( memops_arena *)0)->base), I_Reflect_Type_Ptr, 0, 1, "", "u8", "", 0},
    {"cursor", "ptr_u8", "", (u64)offsetof(memops_arena, cursor), (u64)sizeof(((memops_arena *)0)->cursor), (u64)__alignof__((( memops_arena *)0)->cursor), I_Reflect_Type_Ptr, 0, 1, "", "u8", "", 0},
    {"previous", "ptr_u8", "", (u64)offsetof(memops_arena, previous), (u64)sizeof(((memops_arena *)0)->previous), (u64)__alignof__((( memops_arena *)0)->previous), I_Reflect_Type_Ptr, 0, 1, "", "u8", "", 0},
    {"used", "u64", "", (u64)offsetof(memops_arena, used), (u64)sizeof(((memops_arena *)0)->used), (u64)__alignof__((( memops_arena *)0)->used), I_Reflect_Type_Name, 0, 0, "u64", "", "", 0},
    {"pagesize", "u64", "", (u64)offsetof(memops_arena, pagesize), (u64)sizeof(((memops_arena *)0)->pagesize), (u64)__alignof__((( memops_arena *)0)->pagesize), I_Reflect_Type_Name, 0, 0, "u64", "", "", 0},
    {"npages", "u64", "", (u64)offsetof(memops_arena, npages), (u64)sizeof(((memops_arena *)0)->npages), (u64)__alignof__((( memops_arena *)0)->npages), I_Reflect_Type_Name, 0, 0, "u64", "", "", 0},
};
const i_reflect_type memops_arena_reflect = {"memops_arena", (u64)sizeof(memops_arena), (u64)__alignof__(memops_arena), 6, i_reflect_fields_memops_arena};

#line 1 "<generated>"
static const i_reflect_field i_reflect_fields_memops_arena_temp[] = {
    {"arena", "ptr_memops_arena", "", (u64)offsetof(memops_arena_temp, arena), (u64)sizeof(((memops_arena_temp *)0)->arena), (u64)__alignof__((( memops_arena_temp *)0)->arena), I_Reflect_Type_Ptr, 0, 1, "", "memops_arena", "", 0},
    {"used", "u64", "", (u64)offsetof(memops_arena_temp, used), (u64)sizeof(((memops_arena_temp *)0)->used), (u64)__alignof__((( memops_arena_temp *)0)->used), I_Reflect_Type_Name, 0, 0, "u64", "", "", 0},
};
const i_reflect_type memops_arena_temp_reflect = {"memops_arena_temp", (u64)sizeof(memops_arena_temp), (u64)__alignof__(memops_arena_temp), 2, i_reflect_fields_memops_arena_temp};

#line 1 "<generated>"
static const i_reflect_field i_reflect_fields_payload[] = {
    {"x", "f32", "", (u64)offsetof(payload, x), (u64)sizeof(((payload *)0)->x), (u64)__alignof__((( payload *)0)->x), I_Reflect_Type_Name, 0, 0, "f32", "", "", 0},
    {"y", "ptr_u8", "", (u64)offsetof(payload, y), (u64)sizeof(((payload *)0)->y), (u64)__alignof__((( payload *)0)->y), I_Reflect_Type_Ptr, 0, 1, "", "u8", "", 0},
};
const i_reflect_type payload_reflect = {"payload", (u64)sizeof(payload), (u64)__alignof__(payload), 2, i_reflect_fields_payload};


#line 27 "C:\\devel\\i\\src\\runtime\\memops.i"
bool memops_is_power_of_two(usize x);
#line 31 "C:\\devel\\i\\src\\runtime\\memops.i"
usize memops_align_forward(usize ptr, usize align);
#line 41 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_initialize(memops_arena * arena);
#line 53 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_push(memops_arena * arena, u64 alloc_size, u64 align);
#line 87 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_push_zero(memops_arena * arena, u64 alloc_size, u64 align);
#line 93 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_get_pos(memops_arena * arena);
#line 97 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_set_pos(memops_arena * arena, void * pos);
#line 103 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_pop(memops_arena * arena, u64 alloc_size);
#line 109 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_realloc_(memops_arena * arena, u64 new_alloc_size, void * old_ptr, u64 old_alloc_size, u64 align);
#line 115 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_clear(memops_arena * arena);
#line 120 "C:\\devel\\i\\src\\runtime\\memops.i"
memops_arena_temp memops_arena_temp_begin(memops_arena * arena);
#line 127 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_temp_end(memops_arena_temp temp);
#line 3 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_cstr(const char * text);
#line 11 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i8(i8 x);
#line 15 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i16(i16 x);
#line 19 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i32(i32 x);
#line 23 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i64(i64 x);
#line 27 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u8(u8 x);
#line 31 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u16(u16 x);
#line 35 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u32(u32 x);
#line 39 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u64(u64 x);
#line 43 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_usize(usize x);
#line 47 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_f32(f32 x);
#line 51 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_f64(f64 x);
#line 55 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_char(char x);
#line 59 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_bool(bool x);
#line 67 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_b32(b32 x);
#line 75 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_ptr_char(char * x);
#line 79 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_ptr_const_char(const char * x);
#line 12 "src/main.i"
i32 main(i32 argc, char * * argv);
#line 1 "<generated>"
/* I monomorph: proc Array<T>reserve -> Array_payload_reserve; declared at C:\devel\i\src\runtime\Array.i:9:1; instantiated at src/main.i:32:32 */
#line 9 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_payload Array_payload_reserve(memops_arena * arena, u64 length);
#line 1 "<generated>"
/* I monomorph: proc Array<T>reserve -> Array_i32_reserve; declared at C:\devel\i\src\runtime\Array.i:9:1; instantiated at src/main.i:38:27 */
#line 9 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_i32 Array_i32_reserve(memops_arena * arena, u64 length);
#line 1 "<generated>"
/* I monomorph: proc Node<T>create -> Node_payload_create; declared at C:\devel\i\src\runtime\Node.i:9:1; instantiated at C:\devel\i\src\runtime\List.i:20:22 */
#line 9 "C:\\devel\\i\\src\\runtime\\Node.i"
Node_payload * Node_payload_create(memops_arena * arena, payload data);
#line 1 "<generated>"
/* I monomorph: proc List<T>create -> List_payload_create; declared at C:\devel\i\src\runtime\List.i:10:1; instantiated at src/main.i:47:19 */
#line 10 "C:\\devel\\i\\src\\runtime\\List.i"
List_payload * List_payload_create(memops_arena * arena);
#line 1 "<generated>"
/* I monomorph: proc List<T>append -> List_payload_append; declared at C:\devel\i\src\runtime\List.i:19:1; instantiated at src/main.i:48:5 */
#line 19 "C:\\devel\\i\\src\\runtime\\List.i"
void List_payload_append(memops_arena * arena, List_payload * list, payload item);

#line 27 "C:\\devel\\i\\src\\runtime\\memops.i"
bool memops_is_power_of_two(usize x) {
    #line 28 "C:\\devel\\i\\src\\runtime\\memops.i"
return ((x & (x - 1)) == 0);
}

#line 31 "C:\\devel\\i\\src\\runtime\\memops.i"
usize memops_align_forward(usize ptr, usize align) {
    #line 32 "C:\\devel\\i\\src\\runtime\\memops.i"
usize p = ptr;
    #line 33 "C:\\devel\\i\\src\\runtime\\memops.i"
usize a = align;
    #line 34 "C:\\devel\\i\\src\\runtime\\memops.i"
usize modulo = (p & (a - 1));
    #line 35 "C:\\devel\\i\\src\\runtime\\memops.i"
if ((modulo != 0)) {
        #line 36 "C:\\devel\\i\\src\\runtime\\memops.i"
p += (a - modulo);
    }
    #line 38 "C:\\devel\\i\\src\\runtime\\memops.i"
return p;
}

#line 41 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_initialize(memops_arena * arena) {
    #line 42 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].pagesize = memops_os_page_size();
    #line 43 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].base = memops_os_reserve(max_alloc_size);
    #line 44 "C:\\devel\\i\\src\\runtime\\memops.i"
if ((arena[0].base == 0)) {
        #line 45 "C:\\devel\\i\\src\\runtime\\memops.i"
exit(1);
    }
    #line 47 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].cursor = arena[0].base;
    #line 48 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].previous = arena[0].base;
    #line 49 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].used = 0;
    #line 50 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].npages = 0;
}

#line 53 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_push(memops_arena * arena, u64 alloc_size, u64 align) {
    #line 54 "C:\\devel\\i\\src\\runtime\\memops.i"
usize base_addr = ((usize)(arena[0].base));
    #line 55 "C:\\devel\\i\\src\\runtime\\memops.i"
usize curr_addr = (base_addr + ((usize)(arena[0].used)));
    #line 56 "C:\\devel\\i\\src\\runtime\\memops.i"
usize aligned_addr = memops_align_forward(curr_addr, ((usize)(align)));
    #line 57 "C:\\devel\\i\\src\\runtime\\memops.i"
u64 diff = ((u64)((aligned_addr - curr_addr)));
    #line 58 "C:\\devel\\i\\src\\runtime\\memops.i"
u64 needed = ((arena[0].used + alloc_size) + diff);
    #line 59 "C:\\devel\\i\\src\\runtime\\memops.i"
u64 committed = (arena[0].pagesize * arena[0].npages);
    #line 61 "C:\\devel\\i\\src\\runtime\\memops.i"
if ((needed > committed)) {
        #line 62 "C:\\devel\\i\\src\\runtime\\memops.i"
u64 missing_bytes = (needed - committed);
        #line 63 "C:\\devel\\i\\src\\runtime\\memops.i"
u64 pages_to_commit = (((missing_bytes + arena[0].pagesize) - 1) / arena[0].pagesize);
        #line 64 "C:\\devel\\i\\src\\runtime\\memops.i"
usize commit_addr = (base_addr + ((usize)(committed)));
        #line 65 "C:\\devel\\i\\src\\runtime\\memops.i"
void * r = memops_os_commit(((void *)(commit_addr)), (pages_to_commit * arena[0].pagesize));
        #line 66 "C:\\devel\\i\\src\\runtime\\memops.i"
if ((r == 0)) {
        #line 67 "C:\\devel\\i\\src\\runtime\\memops.i"
printf("memops_arena commit failed at %p!\n", ((void *)(commit_addr)));
        #line 68 "C:\\devel\\i\\src\\runtime\\memops.i"
memops_os_debug_break();
        #line 69 "C:\\devel\\i\\src\\runtime\\memops.i"
exit(1);
    }
        #line 71 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].npages += pages_to_commit;
    }
    #line 74 "C:\\devel\\i\\src\\runtime\\memops.i"
if ((needed > max_alloc_size)) {
        #line 75 "C:\\devel\\i\\src\\runtime\\memops.i"
printf("memops_arena maximum size exceeded!\n");
        #line 76 "C:\\devel\\i\\src\\runtime\\memops.i"
exit(1);
    }
    #line 79 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].used += (alloc_size + diff);
    #line 80 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].previous = arena[0].cursor;
    #line 81 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].cursor = ((u8 *)(aligned_addr));
    #line 82 "C:\\devel\\i\\src\\runtime\\memops.i"
void * oldpos = arena[0].cursor;
    #line 83 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].cursor += alloc_size;
    #line 84 "C:\\devel\\i\\src\\runtime\\memops.i"
return oldpos;
}

#line 87 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_push_zero(memops_arena * arena, u64 alloc_size, u64 align) {
    #line 88 "C:\\devel\\i\\src\\runtime\\memops.i"
void * p = memops_arena_push(arena, alloc_size, align);
    #line 89 "C:\\devel\\i\\src\\runtime\\memops.i"
memset(p, 0, alloc_size);
    #line 90 "C:\\devel\\i\\src\\runtime\\memops.i"
return p;
}

#line 93 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_get_pos(memops_arena * arena) {
    #line 94 "C:\\devel\\i\\src\\runtime\\memops.i"
return (arena[0].base + arena[0].used);
}

#line 97 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_set_pos(memops_arena * arena, void * pos) {
    #line 98 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].cursor = ((u8 *)(pos));
    #line 99 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].used = ((u64)((arena[0].cursor - arena[0].base)));
    #line 100 "C:\\devel\\i\\src\\runtime\\memops.i"
return arena[0].cursor;
}

#line 103 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_pop(memops_arena * arena, u64 alloc_size) {
    #line 104 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].cursor -= alloc_size;
    #line 105 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].used -= alloc_size;
    #line 106 "C:\\devel\\i\\src\\runtime\\memops.i"
return arena[0].cursor;
}

#line 109 "C:\\devel\\i\\src\\runtime\\memops.i"
void * memops_arena_realloc_(memops_arena * arena, u64 new_alloc_size, void * old_ptr, u64 old_alloc_size, u64 align) {
    #line 110 "C:\\devel\\i\\src\\runtime\\memops.i"
void * new_ptr = memops_arena_push(arena, new_alloc_size, align);
    #line 111 "C:\\devel\\i\\src\\runtime\\memops.i"
memcpy(new_ptr, old_ptr, old_alloc_size);
    #line 112 "C:\\devel\\i\\src\\runtime\\memops.i"
return new_ptr;
}

#line 115 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_clear(memops_arena * arena) {
    #line 116 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].cursor = arena[0].base;
    #line 117 "C:\\devel\\i\\src\\runtime\\memops.i"
arena[0].used = 0;
}

#line 120 "C:\\devel\\i\\src\\runtime\\memops.i"
memops_arena_temp memops_arena_temp_begin(memops_arena * arena) {
    #line 121 "C:\\devel\\i\\src\\runtime\\memops.i"
memops_arena_temp t = {};
    #line 122 "C:\\devel\\i\\src\\runtime\\memops.i"
t.arena = arena;
    #line 123 "C:\\devel\\i\\src\\runtime\\memops.i"
t.used = arena[0].used;
    #line 124 "C:\\devel\\i\\src\\runtime\\memops.i"
return t;
}

#line 127 "C:\\devel\\i\\src\\runtime\\memops.i"
void memops_arena_temp_end(memops_arena_temp temp) {
    #line 128 "C:\\devel\\i\\src\\runtime\\memops.i"
temp.arena[0].used = temp.used;
    #line 129 "C:\\devel\\i\\src\\runtime\\memops.i"
temp.arena[0].cursor = (temp.arena[0].base + temp.used);
}

#line 3 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_cstr(const char * text) {
    #line 4 "C:\\devel\\i\\src\\runtime\\Print.i"
if ((text == 0)) {
        #line 5 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("(null)");
        #line 6 "C:\\devel\\i\\src\\runtime\\Print.i"
return;
    }
    #line 8 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%s", text);
}

#line 11 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i8(i8 x) {
    #line 12 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%d", x);
}

#line 15 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i16(i16 x) {
    #line 16 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%d", x);
}

#line 19 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i32(i32 x) {
    #line 20 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%d", x);
}

#line 23 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_i64(i64 x) {
    #line 24 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%lld", x);
}

#line 27 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u8(u8 x) {
    #line 28 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%u", x);
}

#line 31 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u16(u16 x) {
    #line 32 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%u", x);
}

#line 35 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u32(u32 x) {
    #line 36 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%u", x);
}

#line 39 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_u64(u64 x) {
    #line 40 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%llu", x);
}

#line 43 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_usize(usize x) {
    #line 44 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%zu", x);
}

#line 47 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_f32(f32 x) {
    #line 48 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%f", ((f64)(x)));
}

#line 51 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_f64(f64 x) {
    #line 52 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%f", x);
}

#line 55 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_char(char x) {
    #line 56 "C:\\devel\\i\\src\\runtime\\Print.i"
printf("%c", x);
}

#line 59 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_bool(bool x) {
    #line 60 "C:\\devel\\i\\src\\runtime\\Print.i"
if (x) {
        #line 61 "C:\\devel\\i\\src\\runtime\\Print.i"
print_cstr("true");
    } else {
        #line 63 "C:\\devel\\i\\src\\runtime\\Print.i"
print_cstr("false");
    }
}

#line 67 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_b32(b32 x) {
    #line 68 "C:\\devel\\i\\src\\runtime\\Print.i"
if (x) {
        #line 69 "C:\\devel\\i\\src\\runtime\\Print.i"
print_cstr("true");
    } else {
        #line 71 "C:\\devel\\i\\src\\runtime\\Print.i"
print_cstr("false");
    }
}

#line 75 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_ptr_char(char * x) {
    #line 76 "C:\\devel\\i\\src\\runtime\\Print.i"
print_cstr(x);
}

#line 79 "C:\\devel\\i\\src\\runtime\\Print.i"
void print_ptr_const_char(const char * x) {
    #line 80 "C:\\devel\\i\\src\\runtime\\Print.i"
print_cstr(x);
}

#line 12 "src/main.i"
i32 main(i32 argc, char * * argv) {
    #line 13 "src/main.i"
printf("Hello, World!\n");
    #line 15 "src/main.i"
i32 num = 0;
    #line 16 "src/main.i"
print_cstr("num = ");
    #line 16 "src/main.i"
print_i32(num);
    #line 16 "src/main.i"
print_cstr("\n");
    #line 20 "src/main.i"
memops_arena arena = {};
    #line 21 "src/main.i"
memops_arena_initialize(&(arena));
    #line 23 "src/main.i"
payload p = {};
    #line 24 "src/main.i"
const char * name = payload_reflect.name;
    #line 25 "src/main.i"
print_cstr("name ");
    #line 25 "src/main.i"
print_ptr_const_char(name);
    #line 25 "src/main.i"
print_cstr("\n");
    #line 26 "src/main.i"
for (i32 i = 0; (i < payload_reflect.field_count); i += 1) {
        #line 27 "src/main.i"
print_cstr("field[");
        #line 27 "src/main.i"
print_i32(i);
        #line 27 "src/main.i"
print_cstr("] = ");
        #line 27 "src/main.i"
print_ptr_const_char(payload_reflect.fields[i].name);
        #line 27 "src/main.i"
print_cstr("\n");
    }
    #line 30 "src/main.i"
i32 len = 16;
    #line 31 "src/main.i"
memops_arena_temp temp = memops_arena_temp_begin(&(arena));
    #line 32 "src/main.i"
Array_payload payloads = Array_payload_reserve(temp.arena, 128);
    #line 33 "src/main.i"
for (i32 i = 0; (i < 128); i += 1) {
        #line 34 "src/main.i"
payloads.data[i] = ((payload){.x = i});
    }
    #line 36 "src/main.i"
memops_arena_temp_end(temp);
    #line 38 "src/main.i"
Array_i32 numbers = Array_i32_reserve(&(arena), len);
    #line 39 "src/main.i"
for (i32 i = 0; (i < len); i += 1) {
        #line 40 "src/main.i"
numbers.data[i] = i;
    }
    #line 42 "src/main.i"
for (i32 i = 0; (i < len); i += 1) {
        #line 43 "src/main.i"
print_cstr("i = ");
        #line 43 "src/main.i"
print_i32(numbers.data[i]);
        #line 43 "src/main.i"
print_cstr(", ");
    }
    #line 46 "src/main.i"
List_payload * numberchain;
    #line 47 "src/main.i"
numberchain = List_payload_create(&(arena));
    #line 48 "src/main.i"
List_payload_append(&(arena), numberchain, ((payload){.x = 3.16}));
    #line 49 "src/main.i"
List_payload_append(&(arena), numberchain, ((payload){.x = 8.6}));
    #line 50 "src/main.i"
List_payload_append(&(arena), numberchain, ((payload){}));
    #line 52 "src/main.i"
Node_payload * node = numberchain[0].head;
    #line 53 "src/main.i"
for (i32 i = 0; (i < numberchain[0].length); i += 1) {
        #line 54 "src/main.i"
printf("%f", node[0].data.x);
        #line 55 "src/main.i"
node = node[0].next;
    }
    #line 58 "src/main.i"
return 0;
}

#line 1 "<generated>"
/* I monomorph: proc Array<T>reserve -> Array_payload_reserve; declared at C:\devel\i\src\runtime\Array.i:9:1; instantiated at src/main.i:32:32 */
#line 9 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_payload Array_payload_reserve(memops_arena * arena, u64 length) {
    #line 10 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_payload arr = {};
    #line 11 "C:\\devel\\i\\src\\runtime\\Array.i"
if ((length == 0)) {
        #line 12 "C:\\devel\\i\\src\\runtime\\Array.i"
return arr;
    }
    #line 14 "C:\\devel\\i\\src\\runtime\\Array.i"
arr.data = ((payload *)(memops_arena_push_zero(arena, (sizeof(payload) * length), _Alignof(payload))));
    #line 15 "C:\\devel\\i\\src\\runtime\\Array.i"
if ((arr.data == 0)) {
        #line 16 "C:\\devel\\i\\src\\runtime\\Array.i"
printf("I runtime: Array reserve allocation failure\n");
        #line 17 "C:\\devel\\i\\src\\runtime\\Array.i"
exit(1);
        #line 18 "C:\\devel\\i\\src\\runtime\\Array.i"
return arr;
    }
    #line 20 "C:\\devel\\i\\src\\runtime\\Array.i"
arr.length = length;
    #line 21 "C:\\devel\\i\\src\\runtime\\Array.i"
return arr;
}

#line 1 "<generated>"
/* I monomorph: proc Array<T>reserve -> Array_i32_reserve; declared at C:\devel\i\src\runtime\Array.i:9:1; instantiated at src/main.i:38:27 */
#line 9 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_i32 Array_i32_reserve(memops_arena * arena, u64 length) {
    #line 10 "C:\\devel\\i\\src\\runtime\\Array.i"
Array_i32 arr = {};
    #line 11 "C:\\devel\\i\\src\\runtime\\Array.i"
if ((length == 0)) {
        #line 12 "C:\\devel\\i\\src\\runtime\\Array.i"
return arr;
    }
    #line 14 "C:\\devel\\i\\src\\runtime\\Array.i"
arr.data = ((i32 *)(memops_arena_push_zero(arena, (sizeof(i32) * length), _Alignof(i32))));
    #line 15 "C:\\devel\\i\\src\\runtime\\Array.i"
if ((arr.data == 0)) {
        #line 16 "C:\\devel\\i\\src\\runtime\\Array.i"
printf("I runtime: Array reserve allocation failure\n");
        #line 17 "C:\\devel\\i\\src\\runtime\\Array.i"
exit(1);
        #line 18 "C:\\devel\\i\\src\\runtime\\Array.i"
return arr;
    }
    #line 20 "C:\\devel\\i\\src\\runtime\\Array.i"
arr.length = length;
    #line 21 "C:\\devel\\i\\src\\runtime\\Array.i"
return arr;
}

#line 1 "<generated>"
/* I monomorph: proc Node<T>create -> Node_payload_create; declared at C:\devel\i\src\runtime\Node.i:9:1; instantiated at C:\devel\i\src\runtime\List.i:20:22 */
#line 9 "C:\\devel\\i\\src\\runtime\\Node.i"
Node_payload * Node_payload_create(memops_arena * arena, payload data) {
    #line 10 "C:\\devel\\i\\src\\runtime\\Node.i"
Node_payload * node = ((Node_payload *)(memops_arena_push_zero(arena, sizeof(Node_payload), _Alignof(Node_payload))));
    #line 11 "C:\\devel\\i\\src\\runtime\\Node.i"
if ((node == 0)) {
        #line 12 "C:\\devel\\i\\src\\runtime\\Node.i"
printf("I runtime: Node allocation failure\n");
        #line 13 "C:\\devel\\i\\src\\runtime\\Node.i"
exit(1);
    }
    #line 15 "C:\\devel\\i\\src\\runtime\\Node.i"
node[0].next = 0;
    #line 16 "C:\\devel\\i\\src\\runtime\\Node.i"
node[0].data = data;
    #line 17 "C:\\devel\\i\\src\\runtime\\Node.i"
return node;
}

#line 1 "<generated>"
/* I monomorph: proc List<T>create -> List_payload_create; declared at C:\devel\i\src\runtime\List.i:10:1; instantiated at src/main.i:47:19 */
#line 10 "C:\\devel\\i\\src\\runtime\\List.i"
List_payload * List_payload_create(memops_arena * arena) {
    #line 11 "C:\\devel\\i\\src\\runtime\\List.i"
List_payload * list = ((List_payload *)(memops_arena_push_zero(arena, sizeof(List_payload), _Alignof(List_payload))));
    #line 12 "C:\\devel\\i\\src\\runtime\\List.i"
if ((list == 0)) {
        #line 13 "C:\\devel\\i\\src\\runtime\\List.i"
printf("I runtime: List allocation failure\n");
        #line 14 "C:\\devel\\i\\src\\runtime\\List.i"
exit(1);
    }
    #line 16 "C:\\devel\\i\\src\\runtime\\List.i"
return list;
}

#line 1 "<generated>"
/* I monomorph: proc List<T>append -> List_payload_append; declared at C:\devel\i\src\runtime\List.i:19:1; instantiated at src/main.i:48:5 */
#line 19 "C:\\devel\\i\\src\\runtime\\List.i"
void List_payload_append(memops_arena * arena, List_payload * list, payload item) {
    #line 20 "C:\\devel\\i\\src\\runtime\\List.i"
Node_payload * node = Node_payload_create(arena, item);
    #line 21 "C:\\devel\\i\\src\\runtime\\List.i"
if ((list[0].head == 0)) {
        #line 22 "C:\\devel\\i\\src\\runtime\\List.i"
list[0].head = node;
        #line 23 "C:\\devel\\i\\src\\runtime\\List.i"
list[0].length += 1;
        #line 24 "C:\\devel\\i\\src\\runtime\\List.i"
return;
    }
    #line 26 "C:\\devel\\i\\src\\runtime\\List.i"
Node_payload * iter = list[0].head;
    #line 27 "C:\\devel\\i\\src\\runtime\\List.i"
while ((iter[0].next != 0)) {
        #line 28 "C:\\devel\\i\\src\\runtime\\List.i"
iter = iter[0].next;
    }
    #line 30 "C:\\devel\\i\\src\\runtime\\List.i"
iter[0].next = node;
    #line 31 "C:\\devel\\i\\src\\runtime\\List.i"
list[0].length += 1;
}

